name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-with-JDK23:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B test

  sonar:
    needs: test-with-JDK23
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          java-version: 23
          distribution: 'zulu'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zhanj384_cicd-epat

  snyk-scan-sast:
    needs: test-with-JDK23
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan the webapplication
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         ref: master
  #     - name: ZAP Scan
  #       uses: zaproxy/action-full-scan@v0.13.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: "ghcr.io/zaproxy/zaproxy:stable"
  #         target: "https://zestful-peace-production.up.railway.app/person/"
  #         cmd_options: "-a"
